### ISSUE TITLE
Error: Trimmomatic could not remove adapters

### ISSUE THREAD

**Issue by emagallong** [FilAlves/micro-primers#8]
Hello!
I was trying to run micro-primers with my fastq files and I got an error from trimmomatic. In fact, my reads do not have adapters, so 
I do not how to fix this problem. I used the following command: 

python3 micro-primers.py -r1 20230829mtDNATibu02_S2_L001_R1_001.fastq -r2 20230829mtDNATibu02_S2_L001_R2_001.fastq -o Tibu02 -p3 primer3_setting.txt 

And I got this:
CUT3: CCAAGCTTCCCGGGTACCGC CUT5 GCGGTACCCGGGAAGCTTGG
20230829mtDNATibu02_S2_L001_R1_001.fastq 20230829mtDNATibu02_S2_L001_R2_001.fastq CCAAGCTTCCCGGGTACCGC GCGGTACCCGGGAAGCTTGG  50 5 ['c', 'c*', 'p1'] 5 False False 8 primer3_setting.txt False
Trimmomatic working...
Error: Trimmomatic could not remove adapters

Also, I went through the trim_log.txt file and I got this:

TrimmomaticPE: Started with arguments:
 -phred33 20230829mtDNATibu02_S2_L001_R1_001.fastq 20230829mtDNATibu02_S2_L001_R2_001.fastq .temp/trim_out_trimmed_R1.fastq .temp/trim_out_unpaired_R1.fastq .temp/trim_out_trimmed_R2.fastq .temp/trim_out_unpaired_R2.fastq ILLUMINACLIP:software/trim_adapters/TruSeq2-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15
Multiple cores found: Using 4 threads
Using PrefixPair: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'
Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'
Using Long Clipping Sequence: 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
Using Long Clipping Sequence: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
ILLUMINACLIP: Using 1 prefix pairs, 6 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Exception in thread "main" java.io.FileNotFoundException: 20230829mtDNATibu02_S2_L001_R1_001.fastq (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:135)
	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:264)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:539)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)

Could you help me to fix this error? Thanks in advance.

Regards,

Erika

**Comment by FilAlves** [comment]
Hi Erika!

Can you confirm the input files are in micro-primers main folder and not in another folder?
